### ISSUE TITLE
URP support

### ISSUE THREAD

**Issue by proepkes** [insominx/TasharenFogOfWar#1]
Hey, I really like your fog of war but I can't get it to work with URP. Do you have any idea what has to be done to make it compatible with URP?

**Comment by insominx** [comment]
I'm not entirely sure but at a minimum it would require rewriting the shaders.  FYSA, I did not originally author this.  I just patched up it for modern versions of Unity.  Consult the wizards at https://www.tasharen.com/ for more help.
